module.exports = {
  defaultTitle: 'Sameer Waskar',
  logo: 'https://wsameer.github.io/v1/img/sameer-logo.svg',
  author: 'Sameer Waskar',
  url: 'https://wsameer.github.io/v1/',
  legalName: 'Sameer Waskar',
  defaultDescription: 'I’m Sameer and I’m a Full stack engineer!',
  socialLinks: {
    github: 'https://github.com/wsameer',
    linkedin: 'https://www.linkedin.com/in/wsameer',
    instagram: 'https://instagram.com/the_savage_lens',
    youtube: 'https://www.youtube.com/user/wsameer',
    google: 'https://plus.google.com/u/0/wsameer',
  },
  fontAwesomeIcons: 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/solid.min.css',
  simpleLineIcons: 'https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css',
  SocialIcons: [
    {
      id: 1,
      name: 'Github',
      link: 'https://github.com/wsameer',
      icon: '/icons/github.svg',
    },
    {
      id: 2,
      name: 'LinkedIn',
      link: 'https://www.linkedin.com/in/wsameer',
      icon: '/icons/linkedin.svg',
    },
    {
      id: 3,
      name: 'Instagram',
      link: 'https://www.instagram.com/the_savage_lens/',
      icon: '/icons/instagram.svg',
    },
    {
      id: 4,
      name: 'Skype',
      link: 'skype:ftb_sameer',
      icon: '/icons/skype.svg',
    },
  ],
  themeColor: '#6b63ff',
  backgroundColor: '#6b63ff',
  address: {
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    zipCode: '411030',
  },
  contact: {
    email: 'dev.wsameer@gmail.com',
    phone: 'phone number',
  },
  foundingDate: '2020',
};
